# Generated by Django 5.1.6 on 2025-02-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_detection_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewer',
            name='role',
            field=models.IntegerField(default=0),
        ),
    ]
