# Generated by Django 5.1.6 on 2025-03-08 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_detection_app', '0004_admins_article_fakedetection_delete_news_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='viewer',
            name='name',
        ),
    ]
