# Generated by Django 5.1.6 on 2025-03-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_detection_app', '0005_remove_viewer_email_remove_viewer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewer',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='viewer',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
