# Generated by Django 5.1.6 on 2025-03-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_detection_app', '0006_viewer_email_viewer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=20000),
        ),
    ]
